[global]
suppressDeprecationWarnings = true

[server]
runOnSave = true
maxUploadSize = 200
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00A99D"
backgroundColor = "#F4F6F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#004B49"
font = "sans serif"